Import(['compiler'])

examples = ['asciiDump', 'customerReport', 'mapDump']

for name in examples:
    compiler.Program(name , [name +'.cpp'],
             LIBS=['tsio'], LIBPATH=['..'],
             CPPPATH=['.', '..'])


