Import(['compiler'])

examples = ['asciiDump', 'customerReport', 'mapDump', 'showTime']

for name in examples:
    compiler.Program(name , [name +'.cpp'],
             LIBS=['tsio'], LIBPATH=['..'],
             CPPPATH=['.', '..'])


